### PR TITLE
Added new tip to use word under cursor as image's name

### PR DESCRIPTION
**Pull request by gokulmaxi**

### CODE REVIEW

**Comment by ekickx** [comment]
Hello I was thinking that tips's better to be in discussion. You can share your tip [here](https://github.com/ekickx/clipboard-image.nvim/discussions/15).

**Review by ekickx — CHANGES_REQUESTED** [review]
Maybe you can make the **Tips** section to point to the discussion

```markdown
## Tips

Share your tips [here](https://github.com/ekickx/clipboard-image.nvim/discussions/15)
```

Something like that

**Comment by gokulmaxi** [comment]
Sure,i will do that

**Comment by ekickx** [comment]
@gokulmaxi Oh wait you will create new pr? Maybe just post your tips on discussion. I will change the readme by myself

**Pull request closed without merging**
