### PR TITLE
feat: image handler support

### PR DESCRIPTION
**Pull request by codiy1992**
Feat: Add new config item: `img_handler`, It allow user to handle image after pasted (such as tinypng)

`img_handler` must return a function like below 

```lua
img_handler = function () return function (path) return os.execute(string.format('~/.scripts/tinypng.sh -s -f %s &', path)) end end
```

### CODE REVIEW

**Comment by ekickx** [comment]
This seems to be usefull. I will need times to consider merging it to main.

**Comment by codiy1992** [comment]
Thank you! By `img_handler` we can do something like **tinypng** or **upload images to AWS S3**, that is what I think.
But I am new to Lua and my coding may be terrible. sorry!

**Comment by ekickx** [comment]
Nah don't worry about your code. And I have some suggestion. Instead of configuring it like this:
```lua
img_handler = function()
  return function(path)
    ...
  end
end
```
We can do it like this:
```lua
img_handler = function(img)
  ...
end
```

So we don't need to create a function instead of a function. Instead of supplied image's `path`  to the function, we supplied it with `img` table which contain image's name and image's path. I think it can be useful if users want to use image's name in some case so they don't need to manually separate it from its path.

I'll push the change and give me your opinion.

**Comment by ekickx** [comment]
If my explanation is fuzzy, basically you can do this now
```lua
img_handler = function(img)
  os.execute(string.format('~/.scripts/tinypng.sh -s -f %s &', img.path)) 
end
```

**Comment by codiy1992** [comment]
sorry! I have just seen the changes. I am on holiday these days. I totally agree with your changes

**Comment by ekickx** [comment]
Merged. Thanks for your contribution

**Pull request merged**
