### PR TITLE
feat: add `:checkhealth` support

### PR DESCRIPTION
**Pull request by ekickx**

### CODE REVIEW

**Comment by ekickx** [comment]
Hello @geier I just add support for `:checkhealth` and notify user if there's missing dependency to solve this issue #29 . If you have time can you test it?

**Comment by magichan** [comment]
image
but my env is wsl

**Comment by ekickx** [comment]
@magichan 
Actually I don't really know about WSL. Does this plugin work without this pr #21? Because I don't know whether WSL get the clipboard content through `powershell` or `xclip`. If it's the former than I need to merge #21 first.

**Comment by ekickx** [comment]
Also I probably should make the `:checkhealth` message more sensible

**Comment by ekickx** [comment]
@magichan Oh hell it's actually caused by local variable. My bad

**Comment by geier** [comment]
Yes, it's working!

Without pngpaste installed:
Screenshot 2022-04-27 at 14 30 44

with pngpaste installed:
Screenshot 2022-04-27 at 14 34 24

Thanks for cleaning up my mess!

**Comment by ekickx** [comment]
> Yes, it's working!
> 
> Without pngpaste installed: Screenshot 2022-04-27 at 14 30 44
> 
> with pngpaste installed: Screenshot 2022-04-27 at 14 34 24

Nice

> Thanks for cleaning up my mess!

Don't worry about it

**Comment by ekickx** [comment]
Oh yeah I also forgot to add `:checkhealth` message for windows

**Pull request merged**
